# This workflow will do a clean install of node dependencies, build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Autobuild BahmniApps CI

on:
  push:
    branches: [ release-0.92 ]
  pull_request:
    branches: [ release-0.92 ]
defaults:
  run:
    working-directory: ui
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm install -g bower
    - run: npm install -g grunt
    - run: bower install
    - run: grunt
